name: Build MoonTV Docker Image and Export as Artifact

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t moontv:latest .

      - name: Save image as .tar
        run: |
          mkdir -p output
          docker save moontv:latest -o output/moontv.tar

      - name: Upload image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: moontv-docker-image
          path: output/moontv.tar
